const offersStab = [
  {
    'bedrooms':3,
    'city':{
      'location':{
        'lat':52.95029,
        'lng':39.6850183,
        'zoom':10,
      },
      'name':'Brussels',
    },
    'description':' Phasellus eros mauris, condimentum sed nibh vitae, sodales efficitur ipsum. Cras aliquet varius magna, non porta ligula feugiat eget. Nullam nunc ex, convallis sed finibus eget, sollicitudin eget ante.. Nunc fermentum tortor ac porta dapibus',
    'goods':[
      'Dishwasher',
      'Kitchen',
      'Heating',
      'Coffee machine',
      'Cable TV',
      'Washing machine',
    ],
    'host':{
      'avatarUrl':'https://i.pravatar.cc/2',
      'id':1,
      'isPro':false,
      'name':'Fedor',
    },
    'id':1,
    'images':[
      'img/apartment-01.jpg',
    ],
    'isFavorite':true,
    'isPremium':true,
    'location':{
      'lat':52.9392527,
      'lng':4.0813024,
      'zoom':5,
    },
    'maxAdults':1,
    'previewImage':'img/apartment-01.jpg',
    'price':139,
    'rating':1.4,
    'title':'Lorem ipsum dolo',
    'type':'apartment',
  },
  {
    'bedrooms':3,
    'city':{
      'location':{
        'lat':52.9827976,
        'lng':25.1066787,
        'zoom':10,
      },
      'name':'Paris',
    },
    'description':' Nullam nunc ex, convallis sed finibus eget, sollicitudin eget ante',
    'goods':[
      'Dishwasher',
      'Coffee machine',
      'Cable TV',
      'Kitchen',
      'Heating',
      'Washing machine',
    ],
    'host':{
      'avatarUrl':'https://i.pravatar.cc/45',
      'id':2,
      'isPro':true,
      'name':'Gena',
    },
    'id':2,
    'images':[
      'img/apartment-03.jpg',
      'img/apartment-02.jpg',
      'img/apartment-01.jpg',
      'img/apartment-02.jpg',
      'img/apartment-03.jpg',
      'img/apartment-01.jpg',
    ],
    'isFavorite':false,
    'isPremium':true,
    'location':{
      'lat':52.5799583,
      'lng':4.4108526,
      'zoom':7,
    },
    'maxAdults':5,
    'previewImage':'img/apartment-03.jpg',
    'price':132,
    'rating':1.1,
    'title':' Fusce tristique',
    'type':'room',
  },
  {
    'bedrooms':3,
    'city':{
      'location':{
        'lat':52.8408641,
        'lng':31.6061469,
        'zoom':10,
      },
      'name':'Hamburg',
    },
    'description':' Aliquam erat volutpat. Cras aliquet varius magna, non porta ligula feugiat eget. Aliquam id orci ut lectus varius viverra',
    'goods':[
      'Washing machine',
      'Cable TV',
      'Heating',
      'Kitchen',
      'Coffee machine',
      'Dishwasher',
    ],
    'host':{
      'avatarUrl':'https://i.pravatar.cc/37',
      'id':3,
      'isPro':false,
      'name':'Angelina',
    },
    'id':3,
    'images':[
      'img/apartment-03.jpg',
      'img/apartment-02.jpg',
      'img/apartment-02.jpg',
      'img/apartment-03.jpg',
      'img/apartment-02.jpg',
      'img/apartment-01.jpg',
    ],
    'isFavorite':false,
    'isPremium':false,
    'location':{
      'lat':52.6601074,
      'lng':4.9871972,
      'zoom':1,
    },
    'maxAdults':4,
    'previewImage':'img/apartment-03.jpg',
    'price':70,
    'rating':1.9,
    'title':' Cras aliquet va',
    'type':'apartment',
  },
  {
    'bedrooms':4,
    'city':{
      'location':{
        'lat':52.819066,
        'lng':24.4150771,
        'zoom':10,
      },
      'name':'Paris',
    },
    'description':'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    'goods':[
      'Dishwasher',
      'Coffee machine',
      'Kitchen',
      'Washing machine',
      'Cable TV',
      'Heating',
    ],
    'host':{
      'avatarUrl':'https://i.pravatar.cc/46',
      'id':4,
      'isPro':true,
      'name':'Fedor',
    },
    'id':4,
    'images':[
      'img/apartment-03.jpg',
      'img/apartment-03.jpg',
      'img/apartment-02.jpg',
      'img/apartment-02.jpg',
      'img/apartment-02.jpg',
    ],
    'isFavorite':true,
    'isPremium':true,
    'location':{
      'lat':52.3894331,
      'lng':4.5960513,
      'zoom':5,
    },
    'maxAdults':1,
    'previewImage':'img/apartment-03.jpg',
    'price':93,
    'rating':0.7,
    'title':' Cras aliquet va',
    'type':'room',
  },
  {
    'bedrooms':3,
    'city':{
      'location':{
        'lat':52.3529802,
        'lng':20.634975,
        'zoom':10,
      },
      'name':'Cologne',
    },
    'description':' In rutrum ac purus sit amet tempus. Sed sed nisi sed augue convallis suscipit in sed felis. Nullam nunc ex, convallis sed finibus eget, sollicitudin eget ante',
    'goods':[
      'Kitchen',
      'Washing machine',
      'Coffee machine',
      'Dishwasher',
      'Cable TV',
      'Heating',
    ],
    'host':{
      'avatarUrl':'https://i.pravatar.cc/3',
      'id':5,
      'isPro':false,
      'name':'Gena',
    },
    'id':5,
    'images':[
      'img/apartment-03.jpg',
      'img/apartment-01.jpg',
      'img/apartment-01.jpg',
    ],
    'isFavorite':true,
    'isPremium':true,
    'location':{
      'lat':52.6285335,
      'lng':4.9916076,
      'zoom':4,
    },
    'maxAdults':2,
    'previewImage':'img/apartment-03.jpg',
    'price':92,
    'rating':1.3,
    'title':' Cras aliquet va',
    'type':'room',
  },
  {
    'bedrooms':2,
    'city':{
      'location':{
        'lat':52.6026323,
        'lng':46.1740771,
        'zoom':10,
      },
      'name':'Hamburg',
    },
    'description':'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam erat volutpat. In rutrum ac purus sit amet tempus.. Nunc fermentum tortor ac porta dapibus',
    'goods':[
      'Washing machine',
      'Cable TV',
      'Heating',
      'Kitchen',
      'Coffee machine',
      'Dishwasher',
    ],
    'host':{
      'avatarUrl':'https://i.pravatar.cc/26',
      'id':6,
      'isPro':true,
      'name':'Angelina',
    },
    'id':6,
    'images':[
      'img/apartment-01.jpg',
      'img/apartment-03.jpg',
    ],
    'isFavorite':false,
    'isPremium':true,
    'location':{
      'lat':52.6109414,
      'lng':4.5352841,
      'zoom':5,
    },
    'maxAdults':6,
    'previewImage':'img/apartment-01.jpg',
    'price':114,
    'rating':3.8,
    'title':'Lorem ipsum dolo',
    'type':'hotel',
  },
];

export { offersStab };
